### ISSUE TITLE
AWS account and setup

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/atlas#23]
We need an AWS account (e.g., `atlas`) with admin access for @amirrr and I, so we can start to build a deployed system. 

@shapeseas — do you know how to imitate that process?

**Comment by shapeseas** [comment]
There are two steps:

- Set up the AWS account by emailing James Renfro. You need a name that's unique across all AWS namespace (csslab-atlas) and a budget string to support the cost.
- For PennKey users, James can add you. For non-PennKey users, you'll to create an IAM credential. We've shifted away from creating IAM roles tied to people to IAM roles tied to the service accounts so that it's clearer what each identity is doing.

**Comment by markwhiting** [comment]
Thanks, I'll give that a shot.
